<?php
$I = new AcceptanceTester($scenario);
$I->wantTo('sign in my web site');
$I->amOnPage('/');
$I->wait(2);
$I->amOnPage( '/wp-admin' );
$I->wait(2);
$I->fillfield('input#user_login','pooja');
$I->fillfield('input#user_pass','1100');
$I->seeElement( 'input#wp-submit' );
$I->click( 'input#wp-submit' );
$I->wait(2);
$I->seeElement( 'li#menu-dashboard' );
$I->wait(2);
#$I->seeElement( 'wp-menu-name#rtMedia' );
$I->amOnPage( '/wp-admin/admin.php?page=rtmedia-settings');
$I->wait(2);
#$I->amOnPage( '/wp-admin/admin.php?page=rtmedia-settings#rtmedia-display' );
$I->amOnPage('http://testing.local/members-2/pooja/media/');
$I->wait(2);
$I->scrollTo(['css' => '.rtmedia-container ']);
$I->wait(2);
$I->seeElement(['css' => '.rtm-media-options']);
$I->wait(2);
$I->click('.clicker.rtmedia-action-buttons');
$I->wait(5);
$I->seeElement(['css' => '.rtmedia-list']);
$I->wait(2);
$I->seeElement('.rtmedia-item-thumbnail');
$I->wait(2);
$I->click('.rtmedia-item-thumbnail');
$I->wait(2);
$I->seeElement(['css' => '.rtm-media-single-comments']);
$I->click('.rtm-media-single-comments textarea');
$I->wait(2);
#$I->fillfield('input#comment');
#$I->wait(2);
$I->seeElement('.rt_media_comment_submit');
$I->wait(2);
$I->click('input#Comment');
$I->wait(5);
?>