<?php
$I = new AcceptanceTester($scenario);
$I->wantTo('sign in my web site');
$I->amOnPage('/');
$I->wait(2);
$I->amOnPage( '/wp-admin' );
$I->wait(2);
$I->fillfield('input#user_login','pooja');
$I->fillfield('input#user_pass','1100');
$I->seeElement( 'input#wp-submit' );
$I->click( 'input#wp-submit' );
$I->wait(2);
$I->seeElement( 'li#menu-dashboard' );
$I->wait(2);
#$I->seeElement( 'wp-menu-name#rtMedia' );
$I->amOnPage( '/wp-admin/admin.php?page=rtmedia-settings');
$I->amOnPage( '/wp-admin/admin.php?page=rtmedia-settings#rtmedia-display' );
$I->moveMouseOver('li#wp-admin-bar-my-account');
$I->wait(2);
#$I->moveMouseOver('li#wp-admin-bar-my-account-media');
$I->click('li#wp-admin-bar-my-account-media a');
$I->wait(2);
$I->scrollTo(['css' => '.rtmedia-container ']);
$I->wait(2);
$I->seeElement(['css' => '.rtm-media-options']);
$I->wait(2);
$I->click('.clicker.rtmedia-action-buttons');
$I->wait(2);
$I->seeElement(['css' => '.rtmedia-list']);
$I->wait(2);
$I->seeElement('.rtmedia-item-thumbnail');
$I->wait(2);
$I->seeElement('.rtm-media-options .dashicons');
$I->wait(2);
$I->click('.rtm-options .dashicons');
$I->wait(2);
$I->fillfield('input#rtmedia_album_name','MediaAlbum');
$I->fillfield('textarea#rtmedia_album_description','Description');
$I->seeElement('select#rtmedia_select_album_privacy');
$I->click('select#rtmedia_select_album_privacy');
$I->seeElement('button#rtmedia_create_new_album');
$I->click('button#rtmedia_create_new_album');
$I->wait(2);
$I->click('#rtmedia-create-album-modal > button.mfp-close');
$I->wait(2);
$I->click('.rtmedia-item-thumbnail');
$I->wait(2);
$I->seeElement(['css' => '.rtm-media-single-comments']);
$I->wait(2);
$I->click('.rtm-media-single-comments textarea');
$I->wait(2);
$I->fillfield('textarea#comment_content','Test Comment');
$I->wait(2);
$I->seeElement('.rt_media_comment_submit');
$I->wait(2);
$I->click('.rt_media_comment_submit');
$I->wait(2);
$I->click('.rtmedia-container.rtmedia-single-container span.rtm-mfp-close');
$I->seeElement(['css' => '.rtm-media-options.rtm-media-search-enable>*:nth-last-child(2)']);
$I->wait(2);
$I->click('.rtm-media-options.rtm-media-search-enable span.rtmedia-upload-media-link');
$I->wait(2);
// $I->seeElement('rtm-select-files');
// $I->click('#rtm-select-files > button.rtmedia-upload-input');
// $I->wait(2);
?>